### ISSUE TITLE
error in sharing a corpus

### ISSUE THREAD

**Issue by kchall** [PhonologicalCorpusTools/CorpusTools#629]
Tried to share a .corpus and .feature file with another user; she put them in the appropriate folders on her computer, but on trying to load, got the following error:

Traceback (most recent call last):
File "/Users/speechincontext/Documents/Michael/CorpusTools/corpustools/gui/iogui.py", line 62, in run
File "/Users/speechincontext/Documents/Michael/CorpusTools/corpustools/corpus/io/binary.py", line 105, in load_binary
File "/Users/speechincontext/Documents/Michael/CorpusTools/corpustools/corpus/classes/lexicon.py", line 2381, in __setstate__
File "/Users/speechincontext/Documents/Michael/CorpusTools/corpustools/corpus/classes/lexicon.py", line 2365, in __setstate__
File "/Users/speechincontext/Documents/Michael/CorpusTools/corpustools/corpus/classes/lexicon.py", line 2385, in _specify_features
File "/Users/speechincontext/Documents/Michael/CorpusTools/corpustools/corpus/classes/lexicon.py", line 1853, in specify
AttributeError: 'list' object has no attribute 'keys'

**Comment by kchall** [comment]
Resolved...the corpus was being loaded in the old version of PCT; it works in 1.2!
